# Generated by Django 5.2.2 on 2025-09-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_local_host',
            field=models.BooleanField(default=False, help_text='True if user is registered as a local host'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='local_host_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the user became a verified local host', null=True),
        ),
    ]
