# Generated by Django 5.2.2 on 2025-06-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20250605_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='ne_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='ne_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='sw_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='sw_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
