# Generated by Django 5.2.2 on 2025-06-18 14:49

from django.db import migrations


def populate_district_coordinates(apps, schema_editor):
    District = apps.get_model('user_auth', 'District')

    DISTRICTS = [
        # (code, name, sw_longitude, sw_latitude, ne_longitude, ne_latitude)
        ('TVM', 'Thiruvananthapuram', 76.84, 8.28, 77.33, 8.85),
        ('KLM', 'Kollam', 76.43, 8.74, 77.13, 9.07),
        ('PTA', 'Pathanamthitta', 76.45, 9.10, 77.25, 9.65),
        ('ALP', 'Alappuzha', 76.20, 9.23, 76.57, 9.60),
        ('KTM', 'Kottayam', 76.27, 9.25, 76.81, 9.76),
        ('IDK', 'Idukki', 76.65, 9.30, 77.30, 10.20),
        ('EKM', 'Ernakulam', 76.08, 9.62, 76.69, 10.26),
        ('TSR', 'Thrissur', 75.88, 10.15, 76.50, 10.70),
        ('PLK', 'Palakkad', 76.38, 10.40, 76.92, 11.15),
        ('MLP', 'Malappuram', 75.93, 10.70, 76.48, 11.30),
        ('KKD', 'Kozhikode', 75.63, 11.15, 76.12, 11.65),
        ('WYD', 'Wayanad', 75.82, 11.48, 76.25, 11.98),
        ('KGD', 'Kasaragod', 74.85, 12.20, 75.42, 12.70),
        ('KNR', 'Kannur', 75.15, 11.67, 75.72, 12.28),
    ]

    for code, name, sw_lon, sw_lat, ne_lon, ne_lat in DISTRICTS:
        District.objects.filter(code=code).update(
            name=name,
            sw_longitude=sw_lon,
            sw_latitude=sw_lat,
            ne_longitude=ne_lon,
            ne_latitude=ne_lat,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_district_ne_latitude_district_ne_longitude_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_district_coordinates),
    ]
