# Generated by Django 5.2.2 on 2025-06-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_add_geography_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='code',
            field=models.CharField(choices=[('RVR', 'River'), ('FRST', 'Forest'), ('MNTN', 'Mountain'), ('BCH', 'Beache'), ('BCKWTR', 'Backwater')], max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
