# Generated by Django 5.2.2 on 2025-06-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_geography_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
