# Generated by Django 5.2.2 on 2025-09-03 16:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('aadhaar_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be 12 digits', regex='^\\d{12}$')])),
                ('pan_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('services_offered', models.JSONField(default=list, help_text='List of service codes')),
                ('custom_service', models.CharField(blank=True, max_length=200, null=True)),
                ('service_description', models.TextField()),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.CharField(blank=True, max_length=200, null=True)),
                ('documents_provided', models.JSONField(default=list, help_text='List of document codes user can provide')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_host_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local Host',
                'verbose_name_plural': 'Local Hosts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalHostBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ACCOMMODATION', 'Accommodation (Room/House Rental)'), ('FOOD', 'Food Services'), ('GUIDE', 'Local Guiding Services'), ('TRANSPORT', 'Transportation Services'), ('EXPERIENCE', 'Local Experiences & Activities'), ('PHOTOGRAPHY', 'Photography Services'), ('OTHER', 'Other Services')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('host_response', models.TextField(blank=True, null=True)),
                ('traveler_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='local_hosts.localhost')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_host_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalHostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID')], max_length=20)),
                ('document_file', models.FileField(upload_to='local_host_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('local_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='local_hosts.localhost')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('local_host', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='LocalHostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('ACCOMMODATION', 'Accommodation (Room/House Rental)'), ('FOOD', 'Food Services'), ('GUIDE', 'Local Guiding Services'), ('TRANSPORT', 'Transportation Services'), ('EXPERIENCE', 'Local Experiences & Activities'), ('PHOTOGRAPHY', 'Photography Services'), ('OTHER', 'Other Services')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='local_hosts.localhost')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_host_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('local_host', 'reviewer', 'service_type')},
            },
        ),
    ]
