# Generated by Django 5.2.2 on 2025-09-02 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(choices=[('TVM', 'Thiruvananthapuram'), ('KLM', 'Kollam'), ('PTA', 'Pathanamthitta'), ('ALP', 'Alappuzha'), ('KTM', 'Kottayam'), ('IDK', 'Idukki'), ('EKM', 'Ernakulam'), ('TSR', 'Thrissur'), ('PLK', 'Palakkad'), ('MLP', 'Malappuram'), ('KKD', 'Kozhikode'), ('WYD', 'Wayanad'), ('KGD', 'Kannur'), ('KNR', 'Kasargod')], max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ne_longitude', models.FloatField(help_text='Northeast longitude')),
                ('sw_longitude', models.FloatField(help_text='Southwest longitude')),
                ('ne_latitude', models.FloatField(help_text='Northeast latitude')),
                ('sw_latitude', models.FloatField(help_text='Southwest latitude')),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('api_code', models.CharField(help_text='Code used for external API calls', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this geography type')),
            ],
            options={
                'verbose_name_plural': 'Geographies',
                'db_table': 'geographies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_range', models.CharField(blank=True, choices=[('low', 'Budget (< ₹5000)'), ('medium', 'Mid-range (₹5000 - ₹15000)'), ('high', 'Luxury (> ₹15000)')], help_text='Preferred budget range for trips', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_districts', models.ManyToManyField(blank=True, help_text='Preferred Kerala districts', to='preferences.district')),
                ('preferred_geographies', models.ManyToManyField(blank=True, help_text='Preferred geography types', to='preferences.geography')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
    ]
