# Generated by Django 5.2.2 on 2025-09-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20250902_0809'),
        ('preferences', '0002_load_initial_data'),
    ]

    operations = [
    ]
